# Data Prep Assignments

In [5]:
# Import libraries
import numpy as np
import pandas as pd

import warnings

warnings.filterwarnings("ignore")

## Assignment 1: Set the Correct Row Granularity

In [18]:
# 1. Read the Excel spreadsheet into a Pandas DataFrame
entertainment = pd.read_excel('../Data/entertainment.xlsx')

In [19]:
entertainment.head()

     name entertainment  hours_per_week
0   Emily   video_games             5.1
1    Liam   video_games             4.9
2  Olivia   video_games             4.7
3    Noah   video_games             4.6
4     Ava   video_games             5.0

In [20]:
entertainment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            600 non-null    object
 1   entertainment   600 non-null    object
 2   hours_per_week  595 non-null    float64
dtypes: float64(1), object(2)
memory usage: 14.2+ KB

In [21]:
# 2. Check the number of rows and columns
entertainment.shape

(600, 3)

In [22]:
# 3. Determine the row granularity needed
entertainment[entertainment.name == 'Emily']

      name entertainment  hours_per_week
0    Emily   video_games             5.1
150  Emily      tv_shows             5.2
300  Emily        movies             1.4
450  Emily         books             0.5

In [24]:
# 4. Apply the correct DataFrame transformation
entertainment.pivot(index='name', columns='entertainment', values='hours_per_week').reset_index()

entertainment      name  books  movies  tv_shows  video_games
0               Aaliyah    0.5     1.5       4.6          4.9
1               Abigail    NaN     1.4       4.5          4.8
2               Addison    0.5     1.6       4.5          5.0
3               Adeline    3.5     4.4       4.5          6.6
4                 Alana    2.8     3.9       3.8          5.6
..                  ...    ...     ...       ...          ...
145            Winifred    5.2     5.4       4.6          6.9
146              Xanthe    6.0     5.6       4.6          6.7
147                Zara    5.5     6.7       5.7          7.7
148                 Zoe    NaN     1.5       6.1          5.2
149                Zoey    1.2     1.7       4.9          5.1

[150 rows x 5 columns]

In [25]:
# 5. Save the transformation as a new DataFrame
df = entertainment.pivot(index='name', columns='entertainment', values='hours_per_week').reset_index()
df.head()

entertainment     name  books  movies  tv_shows  video_games
0              Aaliyah    0.5     1.5       4.6          4.9
1              Abigail    NaN     1.4       4.5          4.8
2              Addison    0.5     1.6       4.5          5.0
3              Adeline    3.5     4.4       4.5          6.6
4                Alana    2.8     3.9       3.8          5.6

In [26]:
# 6. Check the number of rows and columns
df.shape

(150, 5)

## Assignment 2: Prepare Columns for Modeling

In [ ]:
# 1. Find the missing values

In [ ]:
# 2. Fill in the missing values with zeros

In [ ]:
# 3. Create a new column called video_game_lover for people who played more than 7 hours of video games

## Assignment 3: Feature Engineering

In [ ]:
# 1. Create a column called total_entertainment that sums up all the types of entertainment for each student

In [ ]:
# 2. Create a column called pct_screen that calculates the percent of entertainment that’s on screens (everything except for books) for each student

## Assignment 4: Feature Selection

In [ ]:
# 1. Save the student name column of the DataFrame as its own Series for reference

In [ ]:
# 2. Save the three new columns of the DataFrame as its own DataFrame for modeling – video_game_lover, total_entertainment and pct_screen

## Assignment 5: Feature Scaling

In [ ]:
# 1. Scale the features in the modeling DataFrame so they all have a mean of 0 and a standard deviation of 1

In [ ]:
# 2. Save the output as a final DataFrame that’s ready for modeling

In [ ]:
# 3. Optional: pickle the dataframe for modeling