# Multivariate Time Series Analysis 1

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv('../Data/AirQualityUCI.csv', parse_dates=[['Date', 'Time']], delimiter=";")

In [4]:
df.head()

,Date_Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004 18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN
1,10/03/2004 19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN
2,10/03/2004 20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN
3,10/03/2004 21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN
4,10/03/2004 22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN

In [5]:
print(df.dtypes)

Date_Time         object
CO(GT)            object
PT08.S1(CO)      float64
NMHC(GT)         float64
C6H6(GT)          object
PT08.S2(NMHC)    float64
NOx(GT)          float64
PT08.S3(NOx)     float64
NO2(GT)          float64
PT08.S4(NO2)     float64
PT08.S5(O3)      float64
T                 object
RH                object
AH                object
Unnamed: 15      float64
Unnamed: 16      float64
dtype: object

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
PT08.S1(CO),9357.0,1048.990061,329.832710,-200.0,921.0,1053.0,1221.0,2040.0
NMHC(GT),9357.0,-159.090093,139.789093,-200.0,-200.0,-200.0,-200.0,1189.0
PT08.S2(NMHC),9357.0,894.595276,342.333252,-200.0,711.0,895.0,1105.0,2214.0
NOx(GT),9357.0,168.616971,257.433866,-200.0,50.0,141.0,284.0,1479.0
PT08.S3(NOx),9357.0,794.990168,321.993552,-200.0,637.0,794.0,960.0,2683.0
NO2(GT),9357.0,58.148873,126.940455,-200.0,53.0,96.0,133.0,340.0
PT08.S4(NO2),9357.0,1391.479641,467.210125,-200.0,1185.0,1446.0,1662.0,2775.0
PT08.S5(O3),9357.0,975.072032,456.938184,-200.0,700.0,942.0,1255.0,2523.0
Unnamed: 15,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 16,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date_Time      9471 non-null   object
 1   CO(GT)         9357 non-null   object
 2   PT08.S1(CO)    9357 non-null   float64
 3   NMHC(GT)       9357 non-null   float64
 4   C6H6(GT)       9357 non-null   object
 5   PT08.S2(NMHC)  9357 non-null   float64
 6   NOx(GT)        9357 non-null   float64
 7   PT08.S3(NOx)   9357 non-null   float64
 8   NO2(GT)        9357 non-null   float64
 9   PT08.S4(NO2)   9357 non-null   float64
 10  PT08.S5(O3)    9357 non-null   float64
 11  T              9357 non-null   object
 12  RH             9357 non-null   object
 13  AH             9357 non-null   object
 14  Unnamed: 15    0 non-null      float64
 15  Unnamed: 16    0 non-null      float64
dtypes: float64(10), object(6)
memory usage: 1.2+ MB

In [8]:
df = df.drop('Unnamed: 15', axis=1)

In [9]:
df = df.drop('Unnamed: 16', axis=1)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date_Time      9471 non-null   object
 1   CO(GT)         9357 non-null   object
 2   PT08.S1(CO)    9357 non-null   float64
 3   NMHC(GT)       9357 non-null   float64
 4   C6H6(GT)       9357 non-null   object
 5   PT08.S2(NMHC)  9357 non-null   float64
 6   NOx(GT)        9357 non-null   float64
 7   PT08.S3(NOx)   9357 non-null   float64
 8   NO2(GT)        9357 non-null   float64
 9   PT08.S4(NO2)   9357 non-null   float64
 10  PT08.S5(O3)    9357 non-null   float64
 11  T              9357 non-null   object
 12  RH             9357 non-null   object
 13  AH             9357 non-null   object
dtypes: float64(8), object(6)
memory usage: 1.0+ MB

In [11]:
df.isnull().sum()

Date_Time          0
CO(GT)           114
PT08.S1(CO)      114
NMHC(GT)         114
C6H6(GT)         114
PT08.S2(NMHC)    114
NOx(GT)          114
PT08.S3(NOx)     114
NO2(GT)          114
PT08.S4(NO2)     114
PT08.S5(O3)      114
T                114
RH               114
AH               114
dtype: int64

In [12]:
mask = df.isna().any(axis=1)

In [13]:
rows_with_nans = df[mask]
rows_indices = rows_with_nans.index

In [14]:
print("Rows with missing values:")
print(rows_with_nans)
print("\nIndices of rows with missing values:")
print(rows_indices)

Rows with missing values:
     Date_Time CO(GT)  PT08.S1(CO)  NMHC(GT) C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
9357   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
9358   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
9359   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
9360   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
9361   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
...        ...    ...          ...       ...      ...            ...      ...
9466   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
9467   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
9468   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
9469   nan nan    NaN          NaN       NaN      NaN            NaN      NaN
9470   nan nan    NaN          NaN       NaN      NaN            NaN      NaN

      PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)    T   RH   AH
9357           NaN      NaN           NaN          NaN  NaN  NaN  NaN
9358           NaN      NaN           NaN          NaN  NaN  NaN  NaN
9359           NaN      NaN           NaN          NaN  NaN  NaN  NaN
9360           NaN      NaN           NaN          NaN  NaN  NaN  NaN
9361           NaN      NaN           NaN          NaN  NaN  NaN  NaN
...            ...      ...           ...          ...  ...  ...  ...
9466           NaN      NaN           NaN          NaN  NaN  NaN  NaN
9467           NaN      NaN           NaN          NaN  NaN  NaN  NaN
9468           NaN      NaN           NaN          NaN  NaN  NaN  NaN
9469           NaN      NaN           NaN          NaN  NaN  NaN  NaN
9470           NaN      NaN           NaN          NaN  NaN  NaN  NaN

[114 rows x 14 columns]

Indices of rows with missing values:
Index([9357, 9358, 9359, 9360, 9361, 9362, 9363, 9364, 9365, 9366,
       ...
       9461, 9462, 9463, 9464, 9465, 9466, 9467, 9468, 9469, 9470],
      dtype='int64', length=114)

In [15]:
df.dropna(inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9357 entries, 0 to 9356
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date_Time      9357 non-null   object
 1   CO(GT)         9357 non-null   object
 2   PT08.S1(CO)    9357 non-null   float64
 3   NMHC(GT)       9357 non-null   float64
 4   C6H6(GT)       9357 non-null   object
 5   PT08.S2(NMHC)  9357 non-null   float64
 6   NOx(GT)        9357 non-null   float64
 7   PT08.S3(NOx)   9357 non-null   float64
 8   NO2(GT)        9357 non-null   float64
 9   PT08.S4(NO2)   9357 non-null   float64
 10  PT08.S5(O3)    9357 non-null   float64
 11  T              9357 non-null   object
 12  RH             9357 non-null   object
 13  AH             9357 non-null   object
dtypes: float64(8), object(6)
memory usage: 1.1+ MB

In [17]:
df['Date_Time'] = pd.to_datetime(df.Date_Time, format = '%d/%m/%Y %H.%M.%S')

In [45]:
data = df.drop(['Date_Time'], axis=1)
data.index = df.Date_Time

In [47]:
data.head()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
Date_Time,,,,,,,,,,,,,
2004-03-10 18:00:00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578"
2004-03-10 19:00:00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255"
2004-03-10 20:00:00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502"
2004-03-10 21:00:00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867"
2004-03-10 22:00:00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888"